name: "🚀 New Feature"
description: Have a new idea/feature to help improve the project? Submit it here!
title: "feat: <title>"
labels: ["feature", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        🚀 **New Feature Request**

        We are glad you are interested to execute new feature in the project.:memo:
  - type: textarea
    id: description
    attributes:
      label: Description of the new feature.
      description: Please provide a brief description of the feature you propose. Try to keep it short, simple and to the point.Expalin why do you think this feature is required?
      placeholder: Short and explicit description of the enhancement...
    validations:
      required: true
  - type: textarea
    id: solutionsteps
    attributes:
      label: Describe briefly how you would implement this new feature.
      description: Please provide a solution steps for implementing the enhancement.
      placeholder: Short and explicit description of the solution steps...
      value: |
        Some steps to implement this enhancement-
        1. Step 1
        2. Step 2
        3. Step 3
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots Example (if applicable)
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this enhancement?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Contributor terms
      description: By submitting this issue, you agree to follow our Contributing Instructions. Please read our [Contributing Instructions](https://github.com/jain-rishabh-21/DoctorVerse/blob/main/CONTRIBUTING.md).
      options:
        - label: I agree to follow the Contributing Instructions
          required: true
